version: '3'

services:
  pg-database:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/postgres/entrypoint.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    networks:
      - stack

networks:
  stack:
    driver: bridge

volumes:
  pgdata:
    driver: local
